version: 2
jobs:
  hello:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello!"
  goodbye:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A last goodbye!"
workflows:
  version: 2
  hello_goodbye:
    jobs:
      - hello
      - goodbye
