export const ClarifaiActionTypes = {
	REQUEST_CLARIFAI_PENDING: 'REQUEST_CLARIFAI_PENDING',
	REQUEST_CLARIFAI_SUCCESS: 'REQUEST_CLARIFAI_SUCCESS',
	REQUEST_CLARIFAI_FAILED: 'REQUEST_CLARIFAI_FAILED',
	GET_DETECTED_FACES: 'GET_DETECTED_FACES',
	CLEAR_FACES: 'CLEAR_FACES'
};
